[package]
name = "itsdangerous"
version = "0.4.2"
authors = ["Jake <jh@discordapp.com>"]
edition = "2018"
include = [
    "src/*.rs",
    "Cargo.toml",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/discordapp/itsdangerous-rs"
homepage = "https://github.com/discordapp/itsdangerous-rs"
documentation = "https://docs.rs/itsdangerous"
description = "Rust port of the popular itsdangerous python library for signing strings and sending them over untrusted channels."

[features]
serializer = ["serde", "serde_json"]
nightly = []

[package.metadata.docs.rs]
all-features = true

[dependencies]
hmac = "0.7.0"
sha-1 = "0.8.1"
base64 = "0.10.1"
generic-array = "0.12.0"
typenum = "1.10.0"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
